# GET all movies
GET http://localhost:3000/movies HTTP/1.1
Content-Type: application/json

###

# POST create a new movie
POST http://localhost:3000/movies HTTP/1.1
Content-Type: application/json

{
  "title": "Inception",
  "director": "Christopher Nolan",
  "releaseDate": "2010-07-16",
  "genre": "Sci-Fi",
  "rating": 8.8,
  "duration": 148
}

###

# PUT update an existing movie by ID (example movie)
PUT http://localhost:3000/movies/679553bf79de60af2ecf1e76 HTTP/1.1
Content-Type: application/json

{
  "title": "The Dark Knight",
  "director": "Christopher Nolan",
  "releaseDate": "2008-07-18",
  "genre": "Action",
  "rating": 9.0,
  "duration": 152
}

###

# DELETE remove a movie by ID (example movie)
DELETE http://localhost:3000/movies/6795531e79de60af2ecf1e70 HTTP/1.1
Content-Type: application/json

###

