openapi: 3.0.0
info:
  title: Movie API
  description: API for managing movies
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /movies:
    get:
      summary: Retrieve all movies
      responses:
        "200":
          description: A list of movies
    post:
      summary: Create a new movie
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                director:
                  type: string
                releaseDate:
                  type: string
                genre:
                  type: string
                rating:
                  type: number
                duration:
                  type: number
      responses:
        "201":
          description: Movie created
  /movies/{id}:
    get:
      summary: Retrieve a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the movie
          schema:
            type: string
      responses:
        "200":
          description: A movie object
        "404":
          description: Movie not found
    put:
      summary: Update a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the movie
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                director:
                  type: string
                releaseDate:
                  type: string
                genre:
                  type: string
                rating:
                  type: number
                duration:
                  type: number
      responses:
        "200":
          description: Movie updated
    delete:
      summary: Delete a movie by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the movie
          schema:
            type: string
      responses:
        "200":
          description: Movie deleted
